#!/usr/bin/perl 

use warnings;
use strict;

use File::Basename;
my $dir;

BEGIN {
	$dir .=  (fileparse($0))[1];
}


use lib "$dir";
use Shell_NT;
use Shell_NT::History;

# create new context
#

# main plugins
#
# some parameters:
# know: base directory with config and data

my $shell = Shell_NT->new();

# this shell is only interative!
# so opens the input command line
#

$shell->console();

