#!/usr/bin/perl 

use warnings;
use strict;

# basic shell

use Shell_NT;
use Shell_NT::History;

# create new context
#

# main plugins

my $shell = Shell_NT->new();

# this shell is only interative!
# so opens the input command line
#

$shell->console();

